version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
      - image: redis:latest
      - image: iguagile/iguagile-engine:beta
        environment:
          REDIS_HOST: "localhost:6379"
          GRPC_PORT: "12345"
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet test
