version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
      - image: iguagile/iguagile-engine:beta
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet test
